/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzzy;
import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author ACER
 */
public class report extends javax.swing.JFrame {
Connection koneksi;
    Statement stm;
    ResultSet RsBrg;
    DefaultTableModel tabModel;
    boolean ada=false;
    boolean edit=false;
    private Object[][]dataTable=null;
    Object[]header={"NIM","NAMA","JURUSAN","IPK TERAKHIR","GAJI ORANG TUA","TANGGUNGAN ORANG TUA","DEFUZZYFIKASI","KEPUTUSAN"};
    /**
     * Creates new form report
     */
    public report() {
        initComponents();
              this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/fuzzy/toga2.png")));
    this.setTitle("SISTEM PENYELEKSIAN PENERIMAAN BEASISWA");
        openDB();
        tampil();
        Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
        int x=(dim.width-getWidth())/2;
        int y=(dim.height-getHeight())/2;
        setLocation(x,y);
    }
    
        private void setField(){
        int row=tbl_data.getSelectedRow();
    }
        
        public void openDB(){
        try{
        koneksi kon=new koneksi();
        koneksi=kon.getConnection();
        System.out.println("berhasil");
        }catch(Exception err){
            System.out.println(err);
        }
    }
        
        
    void tampil(){
        tabModel=new DefaultTableModel(null,header);
        try{
            stm=koneksi.createStatement();
            RsBrg=stm.executeQuery("select*from rekap");
            while(RsBrg.next()){
            String[]data={
                
        RsBrg.getString("nim"),RsBrg.getString("nama"),RsBrg.getString("jurusan"),RsBrg.getString("ipk"),RsBrg.getString("gaji"),RsBrg.getString("tanggungan"),RsBrg.getString("defuzzy"),RsBrg.getString("keputusan")};     
        tabModel.addRow(data);
            }
            tbl_data.setModel(tabModel);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e+"Data Gagal Tampil.");
                System.out.println("err:"+e);
        }}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel21 = new fuzzy.panel2();
        clGlossyPanel1 = new GlossyPanel.ClGlossyPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        clPanelTransparan1 = new PanelTransparan.ClPanelTransparan();
        clRoundTransButton1 = new RoundedTransparanButton.ClRoundTransButton();
        clRoundTransButton2 = new RoundedTransparanButton.ClRoundTransButton();
        clRoundTransButton3 = new RoundedTransparanButton.ClRoundTransButton();
        clRoundTransButton4 = new RoundedTransparanButton.ClRoundTransButton();
        clRoundTransButton5 = new RoundedTransparanButton.ClRoundTransButton();
        clPanelTransparan2 = new PanelTransparan.ClPanelTransparan();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        clRoundTransButton6 = new RoundedTransparanButton.ClRoundTransButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1365, 765));

        panel21.setPreferredSize(new java.awt.Dimension(1385, 716));

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SPK Penyeleksian Penerimaan Beasiswa Dengan Methode Fuzzy Logic");

        jLabel31.setFont(new java.awt.Font("Aharoni", 1, 23)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("_");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Aharoni", 1, 23)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("X");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout clGlossyPanel1Layout = new javax.swing.GroupLayout(clGlossyPanel1);
        clGlossyPanel1.setLayout(clGlossyPanel1Layout);
        clGlossyPanel1Layout.setHorizontalGroup(
            clGlossyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clGlossyPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addGap(24, 24, 24))
        );
        clGlossyPanel1Layout.setVerticalGroup(
            clGlossyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clGlossyPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(clGlossyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clGlossyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(jLabel31))
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        clPanelTransparan1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        clRoundTransButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzy/proses.png"))); // NOI18N
        clRoundTransButton1.setText("Proses Fuzzy");
        clRoundTransButton1.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        clRoundTransButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clRoundTransButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clRoundTransButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clRoundTransButton1ActionPerformed(evt);
            }
        });

        clRoundTransButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzy/home.png"))); // NOI18N
        clRoundTransButton2.setText("Home");
        clRoundTransButton2.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        clRoundTransButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clRoundTransButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clRoundTransButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clRoundTransButton2ActionPerformed(evt);
            }
        });

        clRoundTransButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzy/report.png"))); // NOI18N
        clRoundTransButton3.setText("Report");
        clRoundTransButton3.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        clRoundTransButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clRoundTransButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clRoundTransButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clRoundTransButton3ActionPerformed(evt);
            }
        });

        clRoundTransButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzy/plus.png"))); // NOI18N
        clRoundTransButton4.setText("Data\nMahasiswa");
        clRoundTransButton4.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        clRoundTransButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clRoundTransButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clRoundTransButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clRoundTransButton4ActionPerformed(evt);
            }
        });

        clRoundTransButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzy/logout.png"))); // NOI18N
        clRoundTransButton5.setText("Logout");
        clRoundTransButton5.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        clRoundTransButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clRoundTransButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clRoundTransButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clRoundTransButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clPanelTransparan1Layout = new javax.swing.GroupLayout(clPanelTransparan1);
        clPanelTransparan1.setLayout(clPanelTransparan1Layout);
        clPanelTransparan1Layout.setHorizontalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(clRoundTransButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(clRoundTransButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(clRoundTransButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(clRoundTransButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clRoundTransButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        clPanelTransparan1Layout.setVerticalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clRoundTransButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clRoundTransButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clRoundTransButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clRoundTransButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clRoundTransButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        clPanelTransparan2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_data);

        jLabel2.setFont(new java.awt.Font("Aharoni", 1, 20)); // NOI18N
        jLabel2.setText("Data Hasil Keputusan");

        javax.swing.GroupLayout clPanelTransparan2Layout = new javax.swing.GroupLayout(clPanelTransparan2);
        clPanelTransparan2.setLayout(clPanelTransparan2Layout);
        clPanelTransparan2Layout.setHorizontalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(269, 269, 269))
        );
        clPanelTransparan2Layout.setVerticalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        clRoundTransButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzy/cetak.png"))); // NOI18N
        clRoundTransButton6.setText("Cetak");
        clRoundTransButton6.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        clRoundTransButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clRoundTransButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel21Layout = new javax.swing.GroupLayout(panel21);
        panel21.setLayout(panel21Layout);
        panel21Layout.setHorizontalGroup(
            panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clGlossyPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel21Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(clRoundTransButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clPanelTransparan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clPanelTransparan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        panel21Layout.setVerticalGroup(
            panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel21Layout.createSequentialGroup()
                .addComponent(clGlossyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(clPanelTransparan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel21Layout.createSequentialGroup()
                        .addComponent(clRoundTransButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(clPanelTransparan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel21, javax.swing.GroupLayout.PREFERRED_SIZE, 1367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel21, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void clRoundTransButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clRoundTransButton1ActionPerformed
        new fuzifikasi().setVisible(true);
        dispose();
    }//GEN-LAST:event_clRoundTransButton1ActionPerformed

    private void clRoundTransButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clRoundTransButton2ActionPerformed
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_clRoundTransButton2ActionPerformed

    private void clRoundTransButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clRoundTransButton4ActionPerformed
        new utama1().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_clRoundTransButton4ActionPerformed

    private void clRoundTransButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clRoundTransButton5ActionPerformed
       new login().setVisible(true);
        dispose(); 
    }//GEN-LAST:event_clRoundTransButton5ActionPerformed

    private void clRoundTransButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clRoundTransButton3ActionPerformed
        new report().setVisible(true);
        dispose(); 
    }//GEN-LAST:event_clRoundTransButton3ActionPerformed

    private void clRoundTransButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clRoundTransButton6ActionPerformed
         try {
            koneksi kon = new koneksi();
            String fileName = "F:/beasiswa/src/fuzzy/report.jrxml";
            String filetoFill = "F:/beasiswa/src/fuzzy/report.jrxml.jasper";

            JasperCompileManager.compileReportToFile(fileName);
            Map param = new HashMap();
            JasperFillManager.fillReportToFile(filetoFill, param, kon.getConnection());
            JasperPrint jip = JasperFillManager.fillReport(filetoFill, param, kon.getConnection());
            JasperViewer.viewReport(jip, true); 

        } catch (JRException E) {
            System.out.println("gagal");
        }
    }//GEN-LAST:event_clRoundTransButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GlossyPanel.ClGlossyPanel clGlossyPanel1;
    private PanelTransparan.ClPanelTransparan clPanelTransparan1;
    private PanelTransparan.ClPanelTransparan clPanelTransparan2;
    private RoundedTransparanButton.ClRoundTransButton clRoundTransButton1;
    private RoundedTransparanButton.ClRoundTransButton clRoundTransButton2;
    private RoundedTransparanButton.ClRoundTransButton clRoundTransButton3;
    private RoundedTransparanButton.ClRoundTransButton clRoundTransButton4;
    private RoundedTransparanButton.ClRoundTransButton clRoundTransButton5;
    private RoundedTransparanButton.ClRoundTransButton clRoundTransButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JScrollPane jScrollPane1;
    private fuzzy.panel2 panel21;
    private javax.swing.JTable tbl_data;
    // End of variables declaration//GEN-END:variables
}
